on:
  push:
    tags:
      - test-release
      - version-*

name: Prepare release
jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: pyre
            name: pyre-Linux-x86_64-musl.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: pyre.exe
            name: pyre-Windows-x86_64.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: pyre
            name: pyre-Darwin-x86_64.tar.gz
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache cargo & target directories
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "v2"

      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.target, 'musl')

      - name: Install build-essential on Linux
        run: sudo apt-get install --yes build-essential
        if: contains(matrix.platform.target, 'musl')

      # - name: Link g++
      #   run: sudo ln -s /bin/g++ /bin/musl-g++
      #   if: contains(matrix.platform.target, 'musl')

      # Build binary
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      # Publish Release if tags are `test-release'.
      - name: Publish release artifacts
        if: contains(github.ref, 'refs/tags/test-release')
        uses: actions/upload-artifact@v3
        with:
          name: pyre-${{ matrix.platform.os_name }}
          path: "pyre*"

      # Publish Github release if tag begins with `v`
      - name: Publish GitHub release
        if: startsWith( github.ref, 'refs/tags/version-' )
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "pyre*"
          body_path: Changes.md
